name: CICD build

on:
  workflow_dispatch:
    tags:
      - '*'
  pull_request:
    branches: [ uat ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FE: ${{ github.repository }}/react
  IMAGE_NAME_BE: ${{ github.repository }}/node

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS_TOKEN }}

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: false
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}

      - name: Build and push Docker image (FE)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME_FE }}
          tags: ${{steps.tag.outputs.tag}}
          registry: ${{ env.REGISTRY }}
          dockerfile: RN3/frontend/Dockerfile
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS_TOKEN }}

      - name: Build and push Docker image (BE)
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ env.IMAGE_NAME_BE }}
          tags: v0.0.${{github.run_number}}
          registry: ${{ env.REGISTRY }}
          dockerfile: RN3/backend/Dockerfile
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS_TOKEN }}

      
          
##test